services:
  backend:
    build:
      context: ./Backend
    container_name: backend
    ports:
      - "8081:8081"

  frontend:
    build:
      context: ./Frontend
    container_name: frontend
    ports:
      - "4200:80"


  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=h2
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    command:
      - start-dev
      - --import-realm
